#!/bin/bash
echo "🔍 Checking Apple Developer Account Status..."
echo ""
echo "To check if you have a paid developer account:"
echo "1. Open Xcode"
echo "2. Go to: Xcode → Settings (or Preferences)"
echo "3. Click: Accounts tab"
echo "4. Look at your Apple ID"
echo ""
echo "Status indicators:"
echo "- ✅ Shows a team name = Paid account"
echo "- ❌ No team or 'Personal Team' = Free account"
echo ""
echo "CarPlay requires: PAID Apple Developer account ($99/year)"
