#!/bin/bash
echo "🚗 CarPlay Enable Checklist"
echo "========================="
echo ""
echo "Current status: Code is ready, capability not enabled"
echo ""
echo "Required steps:"
echo "1. Go to: https://developer.apple.com/account/resources/identifiers/list"
echo "2. Edit your App ID"
echo "3. Enable 'CarPlay' → 'Communication'"
echo "4. Save and wait 5 minutes"
echo "5. Then run: xcodebuild clean && xcodebuild"
echo ""
echo "Then test in CarPlay simulator"
