#!/bin/bash
echo "🚗 CarPlay Launch Helper"
echo "========================"
echo ""
echo "No simulator is currently running."
echo ""
echo "Here are your options:"
echo ""
echo "1. Open Xcode and run your app (⌘R)"
echo "   Then in Simulator menu: I/O → CarPlay → CarPlay (Car)"
echo ""
echo "2. Or boot simulator first:"
echo "   /Applications/Xcode.app/Contents/Developer/usr/bin/simctl boot 'iPhone 16 Pro'"
echo "   /Applications/Xcode.app/Contents/Developer/usr/bin/simctl ui booted CarPlay"
echo ""
echo "3. Then in Xcode: Run your app (⌘R)"
echo ""
echo "📖 For detailed instructions, see: LAUNCH_CARPLAY_NOW.md"
